name: Build and Test and Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:   

jobs:
  security_tests:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - name: Install dependencies    
      run: npm install
    - name: Run integration tests 
      run: npm run test-security-check

  integration_tests:

    runs-on: ubuntu-latest
    needs: security_tests
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - name: Install dependencies    
      run: npm install
    - name: Run integration tests 
      run: npm test

  deploy_render:
    runs-on: ubuntu-latest
    needs: integration_tests
    steps:
          - name: Deploy to production
            uses: johnbeynon/render-deploy-action@v0.0.8
            with:
              service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
              api-key: ${{ secrets.MY_RENDER_API_KEY }}
    
